// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type RuntimeProcess = {
  env?: Record<string, string | undefined>;
};

const viteEnv = import.meta.env;
const runtimeEnv =
  typeof process !== 'undefined' ? (process as RuntimeProcess).env : undefined;

function readEnv(...keys: string[]) {
  for (const key of keys) {
    const value = viteEnv[key] || runtimeEnv?.[key];
    if (value) return value;
  }
  return undefined;
}

function createSupabaseClient() {
  // Lovable Cloud may expose either the publishable-key or anon-key naming convention.
  const SUPABASE_URL = readEnv('VITE_SUPABASE_URL', 'SUPABASE_URL');
  const SUPABASE_PUBLISHABLE_KEY = readEnv(
    'VITE_SUPABASE_PUBLISHABLE_KEY',
    'VITE_SUPABASE_ANON_KEY',
    'SUPABASE_PUBLISHABLE_KEY',
    'SUPABASE_ANON_KEY',
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
